### ISSUE TITLE
Expand Promise example

### ISSUE THREAD

**Issue by jbmonroe** [mindeavor/es-pipeline-operator#25]
Sorry, I'm not following at all how *promise* ends up available to *catchError()* and *then()*.  If all of that example code exists under the aegis of a larger object implementation, it would be clearer to the reader if he or she could see that.

It's also not completely clear to me how this is better than just capturing the exception via an ordinary Promise#catch and vetting the exception type inside the function.  If it isn't what you want, just re-throw from there.  No extension to the Promise prototype would be required.  What am I missing here?

**Comment by mindeavor** [comment]
`promise` ends up to `catchError()` via the operator. Following the rule `x |> f` is equivalent to `f(x)`, we can deduce the following:

```js
fetchPlayers().then( processGames )
  |> catchError( ProcessError, err => [] )

// Equivalent to:

catchError( ProcessError, err => [] )(
  fetchPlayers().then( processGames )
)
```

This works because `catchError()` return an arrow function that expects a promise. Its primary purpose is to remove the boilerplate of catching specific errors – something [Bluebird.js has built in](http://bluebirdjs.com/docs/api/catch.html), and something I use quite often.

**Comment by jbmonroe** [comment]
Yeah, I thought I was reading that incorrectly.  Thanks!
