### ISSUE TITLE
Function composition models pipelines

### ISSUE THREAD

**Issue by mlanza** [mindeavor/es-pipeline-operator#304]
Let's start with the standard F# pipeline as implemented by Babel:

```js
const a = x 
  |> f(?, 1)
  |> g
  |> h
```

This gives you `a` where `x`, some value, is passed down the pipeline.  Function composition syntax can be similarly achieved.

```js
const y = // x is omitted 
  |> f(?, 1)
  |> g
  |> h

//this syntax is equivalent to:

const y = comp(h, g, f(?, 1));  

/* so that... */

const a = y(x);

```

Given a basic pipeline syntax, one drops the initial input argument and, conveniently, ends up with a composed function.  This makes sense given that function composition and pipelines are so closely related.

There should be little reason, once the pipeline syntax is settled, that function composition syntax couldn't tag along.

**Comment by snatvb** [comment]
question symbol aready assiciated with optional, better than sharp - `#` I don't know, maybe is percent(`%`) could be, but `#` looks better and don't uses as math opeator, that can confuse
```ts
const y = // x is omitted 
  |> f(#, 1)
  |> g
  |> h
```

**Comment by bogdanbiv** [comment]
The F# pipeline proposal was already rejected by TC39 several times.
The topic topic (?, # or %) is being discussed in another issue ( #91 ). 

Mind you, the issue of a topic token is stuck because no one is able to find a reasonable proposal. We are down to two characters topic tokens and we're still stuck. One character tokens (all of: _@#$%?_) have already been hashed to bits (no pun intended here). Please do check if your topic token has already been discussed. 

As a developer interested in this proposal I also tried to contribute ideas to the topic token, but it seems some have found my proposals as if I were digging in the cemetery for corpses of old discussions :-). I'm telling you this to understand the experience you will receive. People are already tired of the discussion of picking a topic token, which effectively kills this proposal :-(.

This being said I would recommend closing this issue, as there is nothing to be further discussed here.
