### ISSUE TITLE
Are there no better alternatives to `|>` character combination

### ISSUE THREAD

**Issue by wheresrhys** [mindeavor/es-pipeline-operator#37]
Is `|>` the best character combination available for the operator? `|` - the ideal - is already taken by bitwise operators, but I worry that with the proposed syntax it's too easy to miss a `|` or `>` and still have syntactically valid code, leading to hard to trace bugs e.g.

```
var isValid = score
  |> isNumeric
  > isGreaterThanZero
```

Would generally give `false` every time.

Have any other character combinations been considered? 

(Note: I've read https://github.com/mindeavor/es-pipeline-operator/issues/4, but it mostly concerns syntax for multi-parametered functions)

**Comment by TehShrike** [comment]
Whether or not it's the best in theory, in practice [the other languages with this functionality](https://github.com/mindeavor/es-pipeline-operator#es7-proposal-the-pipeline-operator) seem to be using `|>`, so it would probably be best not to pick a new character so that the feature would be more readable to people coming from those other function-oriented language (and vice-versa for JavaScript folks moving to those other languages).

**Comment by barneycarroll** [comment]
The same argument could be made for arrow functions, and people are making them. `=` separated from `>` by whitespace makes a huge difference. I would be interested in the collected observations of people who've seen this to be a problem.

**Comment by jasmith79** [comment]
Trying and failing to think of a situation in which `=\s+>` isn't a parse Error. That sounds more like a theoretical concern that a practical one. In regards to the pipe operator, the obvious solution is linting (much like assignment in a conditional instead of an equality comparison), although I realize that playing the tools card is a little weak. That being said, as TehShrike pointed out if its good enough for the laundry list of functional languages in the readme (where its obviously not enough of a problem to outweigh usefulness), its good enough for js.

**Comment by wheresrhys** [comment]
Somehow I missed the reference to other languages in the README. Seems reasonable to follow their lead on syntax

**Comment by jamen** [comment]
I like the syntax.  It is an pipe with an arrow, "pipe to".  Also feels reminiscent of arrow functions.
